# ================
# READ FILE ACTION
# ================

name: read-file-action
author: Shresht7
description: A GitHub Action to read a file and export its contents

runs:
  using: node16
  main: dist/index.js

branding:
  icon: file-text
  color: red

# Inputs
# ======

inputs:
  path:
    description: Path to the file to read (can be a URL)
    required: true

  parse:
    description: Parse the file contents as `yaml` or `json`. If `true` will try to automatically determine the file-extension or you can also set it to `yaml` or `json` manually. If `false`, it will return the raw string
    required: false

# Outputs
# =======

outputs:
  contents:
    description: The contents of the file
