# ================
# READ FILE ACTION
# ================

name: read-file-action
author: Shresht7
description: A GitHub Action to read a file and export its contents

runs:
  using: node16
  main: dist/index.js

branding:
  icon: file-text
  color: red

# Inputs
# ======

inputs:
  src:
    description: Path to the file to read (can be a URL)
    required: true

  type:
    description: Parse the file contents as `yaml` or `json`
    required: false

# Outputs
# =======

outputs:
  contents:
    description: The contents of the file
