# ===========
# TEST ACTION
# ===========

name: Test-Read-File

# Activation Events
# =================

on:
  # Manual workflow dispatch
  workflow_dispatch:
    inputs:
      src:
        description: Path to the file to read
        required: true
        default: ./README.md

      type:
        description: Parse file as (`yaml` | `json`)
        required: false

# Jobs
# ====

jobs:
  read-file:
    runs-on: ubuntu-latest
    steps:
      # Actions Checkout ✅
      # ===================

      - name: checkout
        uses: actions/checkout@v3

      # Read File 📄
      # ============

      - name: read-file
        id: read-file
        uses: ./
        with:
          src: ${{ github.event.inputs.src }}
          type: ${{ github.event.inputs.type }}

      # Show Output 📱
      # ==============

      - name: show output
        run: echo ${{ steps.read-file.outputs.contents }}
