# ================
# READ FILE ACTION
# ================

name: Test Read File Action

# Activation Events
# =================

on:
  # Manual workflow dispatch
  workflow_dispatch:
    inputs:
      path:
        description: Path to the file to read
        required: true
        default: ./README.md

      parse:
        description: Parse file as `yaml` or `json`
        required: false

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      # Actions Checkout ✅
      # ===================

      - name: checkout
        uses: actions/checkout@v3

      # Read File 📄
      # ============

      - name: read-file
        id: read-file
        uses: ./
        with:
          path: ${{ github.event.inputs.path }}
          parse: ${{ github.event.inputs.parse }}

      # Show Output 📱
      # ==============

      - name: show output
        run: echo ${{ toJSON(steps.read-file.outputs.contents) }}
